version: '2'
#networks:
#  fastdfs-net:
#    external: true
networks:
  fastdfs-net:
    driver: bridge
services:
  tracker1:
    container_name: tracker1
    image: bbjreg.svicloud.com/tools/fastdfs:V3.0
    ports:
    - 22122:22122/tcp
    command: tracker
    #network_mode: host
    networks:
      - fastdfs-net
    volumes:   
      - /opt/fdfs/tracker1:/var/fdfs
    labels:
      io.rancher.scheduler.affinity:host_label: fastdfs=1
  tracker2:
    container_name: tracker2
    image: bbjreg.svicloud.com/tools/fastdfs:V3.0
    command: tracker
    ports:
    - 22122:22122/tcp
    #network_mode: host
    networks:
      - fastdfs-net
    volumes:   
      - /opt/fdfs/tracker2:/var/fdfs
    labels:
      io.rancher.scheduler.affinity:host_label: fastdfs=2
  storage0:
    container_name: storage0
    image: bbjreg.svicloud.com/tools/fastdfs:V3.0
    ports:
    - 23000:23000/tcp
    command: storage
    #network_mode: host  
    networks:
      - fastdfs-net
    environment:
      - TRACKER_SERVER=192.168.100.114:22122
      - TRACKER_SERVER=192.168.100.115:22122
    volumes: 
      - /opt/fdfs/storage0:/var/fdfs
    labels:
      io.rancher.scheduler.affinity:host_label: fastdfs=1
  storage1:
    container_name: storage1
    image: bbjreg.svicloud.com/tools/fastdfs:V3.0
    ports:
    - 23000:23000/tcp
    command: storage
    #network_mode: host  
    networks:
      - fastdfs-net
    environment:
      - TRACKER_SERVER=192.168.100.114:22122
      - TRACKER_SERVER=192.168.100.115:22122
    volumes: 
      - /opt/fdfs/storage1:/var/fdfs
    labels:
      io.rancher.scheduler.affinity:host_label: fastdfs=2
  #  storage2:
  #   container_name: storage2
  #   image: ygqygq2/fastdfs-nginx:latest
  #   command: storage
  #   #network_mode: host  
  #   networks:
  #     - fastdfs-net  
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #     - GROUP_NAME=group2
  #     - PORT=24000
  #   volumes: 
  #     - /var/fdfs/storage2:/var/fdfs           
                    
